default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local_default: &local_default
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: pg181920

development:
  <<: *local_default
  database: test_app_development

test:
  <<: *local_default
  database: test_app_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    <<: *primary_production
